name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libpango-1.0-0 libpango1.0-dev libatk1.0-0 libatk1.0-dev libgtk-3-dev
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
